project:
  enableReceiver: true
  file:
    backupDir: d:\backup
    sendDir: d:\test
  mq:
    ccsid: 1381
    channel: CLIENT.QM_APPLE
    host: 192.168.1.168
    password: lyh130182
    port: 1414
    queue: Q1
    queue-manager: QM_APPLE
    receive-timeout: 2000
    username: Administrator